[general]
remoteAppDB = "True" # If True use postgres otherwise localStorage

[localStorage]
sqliteDB = "appData/accorns.db"
duckDB = "appData/vectordb.duckdb"

[postgres]
host = "localhost"
port = 5432
# Usernames scuirrel and accorns were created during setup
# Password retrieved from POSTGRES_PASS_SCUIRREL and POSTGRES_PASS_ACCORNS environment variables

[LLM]
gptModel = "gpt-3.5-turbo-0125"  # use gpt-3.5-turbo-0125 or gpt-4
# Make sure OPENAI_API_KEY is set as environment variable
# Make sure OPENAI_ORGANIZATION is set as environment variable
