[general]
remoteAppDB = "False" # If True use postgres otherwise localStorage
addDemo = "True"

[localStorage]
sqliteDB = "appData/accorns.db"
duckDB = "appData/vectordb.duckdb"

[postgres]
host = "localhost"
port = 5432
# Usernames scuirrel and accorns were created during setup
# Password retrieved from POSTGRES_PASS_SCUIRREL and POSTGRES_PASS_ACCORNS environment variables

[LLM]
gptModel = "gpt-3.5-turbo-0125"  # use gpt-3.5-turbo-0125 or gpt-4
# Make sure OPENAI_API_KEY is set as environment variable
# Make sure OPENAI_ORGANIZATION is set as environment variable

[auth]
personalInfo = "False" # If True, will collect name and email
validEmail = "^[\\w.-]+@([\\w-]+\\.)+[\\w-]{2,4}$" # which email addresses can register
